# Back propagation using pytorch

In [1]:
import torch

In [2]:
x=torch.tensor(6.0, requires_grad=True)

In [3]:
x

tensor(6., requires_grad=True)

In [4]:
y=x**2
y

tensor(36., grad_fn=<PowBackward0>)

In [5]:
## Back propagation y=2x
y.backward()

In [6]:
print(x.grad)

tensor(12.)


In [7]:
lst=[[2.,4.,6.],[1.,3.,5.],[1.,2.,3.]]
torch_input=torch.tensor(lst,requires_grad=True)

In [8]:
torch_input

tensor([[2., 4., 6.],
        [1., 3., 5.],
        [1., 2., 3.]], requires_grad=True)

In [9]:
##y=x**3+x**2
##y=3x**2+2x
y=torch_input**3+torch_input**2

In [10]:
y

tensor([[ 12.,  80., 252.],
        [  2.,  36., 150.],
        [  2.,  12.,  36.]], grad_fn=<AddBackward0>)

In [11]:
z=y.sum()

In [12]:
z

tensor(582., grad_fn=<SumBackward0>)

In [13]:
z.backward()

In [14]:
torch_input.grad

tensor([[ 16.,  56., 120.],
        [  5.,  33.,  85.],
        [  5.,  16.,  33.]])