In [1]:
import torch

In [2]:
import numpy as np

In [3]:
lst=[3,4,5,6]
arr=np.array(lst)

In [4]:
arr

array([3, 4, 5, 6])

In [5]:
arr.dtype

dtype('int32')

## convert numpy to pytorch

In [6]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [7]:
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [8]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [9]:
tensors[2]=3

In [10]:
tensors

tensor([3, 4, 3, 6], dtype=torch.int32)

In [11]:
arr

array([3, 4, 3, 6])

In [12]:
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([3, 4, 3, 6], dtype=torch.int32)

In [13]:
tensor_arr[3]=100
print(tensor_arr)
print(arr)

tensor([  3,   4,   3, 100], dtype=torch.int32)
[3 4 3 6]


In [14]:
##zeros amd ones
torch.zeros(2,3,dtype=torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(3,4,dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [16]:
a=torch.tensor(np.arange(0,10).reshape(2,5))

In [17]:
a

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]], dtype=torch.int32)

In [18]:
a[:,0:2]

tensor([[0, 1],
        [5, 6]], dtype=torch.int32)

# Arithmetic Operation

In [19]:
a=torch.tensor([3,4,5],dtype=torch.float)
b=torch.tensor([2,4,6],dtype=torch.float)
print(a+b)

tensor([ 5.,  8., 11.])


In [20]:
torch.add(a,b)

tensor([ 5.,  8., 11.])

In [21]:
c=torch.zeros(3)

In [22]:
torch.add(a,b,out=c)

tensor([ 5.,  8., 11.])

In [23]:
c

tensor([ 5.,  8., 11.])

In [24]:
x=torch.tensor([2,4,6],dtype=torch.float)
y=torch.tensor([1,3,5],dtype=torch.float)

In [25]:
##tensor[3,7,11]
torch.add(x,y).sum()

tensor(21.)

# Dot Product and Multi Operations

In [26]:
p=torch.tensor([3,5,7],dtype=torch.float)
q=torch.tensor([3,6,9],dtype=torch.float)

In [27]:
p.mul(q)

tensor([ 9., 30., 63.])

In [28]:
##3*3+5*6+7*9
p.dot(q)

tensor(102.)

In [29]:
## Matrix Multiplication
c=torch.tensor([[1,4,2],[1,2,3]],dtype=torch.float)
d=torch.tensor([[3,5],[5,7],[7,9]],dtype=torch.float)

In [30]:
torch.matmul(c,d)

tensor([[37., 51.],
        [34., 46.]])

In [31]:
torch.mm(c,d)

tensor([[37., 51.],
        [34., 46.]])

In [32]:
c@d

tensor([[37., 51.],
        [34., 46.]])